### ISSUE TITLE
Last release does not include latest fixes

### ISSUE THREAD

**Issue by VividVisions** [archfirst/joinjs#7]
Version 0.4.0 at NPM does not seem to include the fixes of PR #3 for empty associations/collections. It'd be great to have a version 0.4.1 with the fix.

(It cost me quite a bit of time to investigate and fix it myself only to realize that there already has been a merged PR for it.)

**Comment by nareshbhatia** [comment]
Sure, will release a new version this week.

**Comment by VividVisions** [comment]
Great, thank you!

**Comment by nareshbhatia** [comment]
@VividVisions, released 0.4.1. Please make sure it works with your app.

**Comment by nareshbhatia** [comment]
@VividVisions, please note that because I upgraded from Babel 5 to Babel 6, you will have to `require()` JoinJS slightly differently:

**Before (JoinJS v0.4.0)**

    var joinjs = require('join-js');

**After (JoinJS v0.4.1)**

    var joinjs = require('join-js').default;

You can find the reason for this in [this article](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0).

Of course, if you are using ES6 imports, then you should simply be able to do this:

    import joinjs from 'join-js';

**Comment by VividVisions** [comment]
Works! Thank you!
