### ISSUE TITLE
map function return error of undefined function

### ISSUE THREAD

**Issue by formanite-20** [archfirst/joinjs#9]
Hi
New changes give error on map of undefined function. However I resolved this by join-js.default.map. Kindly maintain version incase of any change in the code.

**Comment by nareshbhatia** [comment]
This was the result of moving from Babel 5 to Babel 6 where they fixed how exports should be done (Babel 5 actually did it the wrong way). You are right, I should have bumped the minor version, but this one slipped by. I have documented it though in the tutorial.

**Comment by chrisburrus** [comment]
I don't see any documentation on this. 

Just as a note, we were using version 0.40, and this actually broke our code. I had to manually fix all of it to do Join.default.map instead of Join.map. Then I had to dig through closed issues to actually finally find the root cause the root fix.

I don't want to overly complain about free code, but the ball was seriously dropped on this one.

**Comment by nareshbhatia** [comment]
@chrisburrus, sorry, my apologies. I will add a note in the README.

**Comment by nareshbhatia** [comment]
Note added.
